### ISSUE TITLE
能问一下怎么用吗

### ISSUE THREAD

**Issue by al-wei** [Trcmoe/LoadedModsExporter-Python#3]
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\86150\Downloads\LoadedModsExporter-Python-main\LME_Final.py
Traceback (most recent call last):
  File "C:\Users\86150\Downloads\LoadedModsExporter-Python-main\LME_Final.py", line 3, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

网上看了一下.py怎么用，然后就报这些内容。

**Comment by Trcmoe** [comment]
你需要安装toml库，如果安装过pip，可以在终端里输入`pip install toml`。

**Comment by al-wei** [comment]
> 你需要安装toml库，如果安装过pip，可以在终端里输入`pip install toml`。

可以了但是1.19.2，233个模组一个不差，1.12.2，255个列表显示却只有识别了geckolib3、i18nupdatemod两个。这是怎么回事呢。

**Comment by Trcmoe** [comment]
可以把1.12.2版本的模组列表发一下吗？

**Comment by al-wei** [comment]
> 可以把1.12.2版本的模组列表发一下吗？

https://www.curseforge.com/minecraft/modpacks/a-l/files/5137111/dependencies

**Comment by Trcmoe** [comment]
这个程序处理Forge模组还是有点问题，我会抽时间修一下。

**Comment by al-wei** [comment]
> 这个程序处理Forge模组还是有点问题，我会抽时间修一下。

之前没看到，还有一些问题，这个版本号问题，而且很多。
随处可见这种。
![image](https://github.com/Trcmoe/LoadedModsExporter-Python/assets/145486869/97b11f04-2366-452f-b19b-76c0f0ccf836)
![image](https://github.com/Trcmoe/LoadedModsExporter-Python/assets/145486869/7c587667-049c-49f7-9f85-98dc8d85a9ee)

**Comment by Trcmoe** [comment]
这主要是因为有的模组作者会把版本号以变量的形式写在代码里，我没有开发Forge模组的经验，不太懂这样怎么workaround。

**Comment by lactobionicAcid** [comment]
> 这主要是因为有的模组作者会把版本号以变量的形式写在代码里，我没有开发Forge模组的经验，不太懂这样怎么workaround。

`${file.jarVersion}`默认引用的是.\META-INF\MANIFEST.MF中`Implementation-Version`这一变量。
理论上只要再加一个读取MANIFEST.MF的功能就行了...

**Comment by Trcmoe** [comment]
> > 这个程序处理Forge模组还是有点问题，我会抽时间修一下。
> 
> 之前没看到，还有一些问题，这个版本号问题，而且很多。 随处可见这种。 ![image](https://private-user-images.githubusercontent.com/145486869/321249475-97b11f04-2366-452f-b19b-76c0f0ccf836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODYxNDksIm5iZiI6MTcyMDQ4NTg0OSwicGF0aCI6Ii8xNDU0ODY4NjkvMzIxMjQ5NDc1LTk3YjExZjA0LTIzNjYtNDUyZi1iMTliLTc2YzBmMGNjZjgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMDQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGEwOWJmZWM4NjVkZDhhNTAwMTZmMzc4ZWNmZjMwNTU0YzA3NTBkODZjNmRlMTY1MmRlN2Q4OTY0NTAxY2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nzExU06iCZwB-OHwB9dYBq75fxRQyvxzQ4B_-gMKmNw) ![image](https://private-user-images.githubusercontent.com/145486869/321249776-7c587667-049c-49f7-9f85-98dc8d85a9ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODYxNDksIm5iZiI6MTcyMDQ4NTg0OSwicGF0aCI6Ii8xNDU0ODY4NjkvMzIxMjQ5Nzc2LTdjNTg3NjY3LTA0OWMtNDlmNy05Zjg1LTk4ZGM4ZDg1YTllZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMDQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjhkMDhmYjdjMWUzODNmNzAzMjVhNzU4ZTRkOTVkYzFmZGVkNDVkNjZhZDAzNWE0ODRiZWQ3NGVmNGQxYWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7OxedXmY-o9L_Mgla5XNLMKRTDef6MRjF0ivx-l5Jus)

新提交的版本应该能处理这种情况了，我试了一下至少Kiwi可以正常识别，如果还有我没预料到情况，就把这个issue重新打开。

**Comment by al-wei** [comment]
> > > 这个程序处理Forge模组还是有点问题，我会抽时间修一下。
> > 
> > 
> > 之前没看到，还有一些问题，这个版本号问题，而且很多。 随处可见这种。 ![image](https://private-user-images.githubusercontent.com/145486869/321249475-97b11f04-2366-452f-b19b-76c0f0ccf836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODYxNDksIm5iZiI6MTcyMDQ4NTg0OSwicGF0aCI6Ii8xNDU0ODY4NjkvMzIxMjQ5NDc1LTk3YjExZjA0LTIzNjYtNDUyZi1iMTliLTc2YzBmMGNjZjgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMDQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGEwOWJmZWM4NjVkZDhhNTAwMTZmMzc4ZWNmZjMwNTU0YzA3NTBkODZjNmRlMTY1MmRlN2Q4OTY0NTAxY2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nzExU06iCZwB-OHwB9dYBq75fxRQyvxzQ4B_-gMKmNw) ![image](https://private-user-images.githubusercontent.com/145486869/321249776-7c587667-049c-49f7-9f85-98dc8d85a9ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODYxNDksIm5iZiI6MTcyMDQ4NTg0OSwicGF0aCI6Ii8xNDU0ODY4NjkvMzIxMjQ5Nzc2LTdjNTg3NjY3LTA0OWMtNDlmNy05Zjg1LTk4ZGM4ZDg1YTllZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMDQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjhkMDhmYjdjMWUzODNmNzAzMjVhNzU4ZTRkOTVkYzFmZGVkNDVkNjZhZDAzNWE0ODRiZWQ3NGVmNGQxYWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7OxedXmY-o9L_Mgla5XNLMKRTDef6MRjF0ivx-l5Jus)
> 
> 新提交的版本应该能处理这种情况了，我试了一下至少Kiwi可以正常识别，如果还有我没预料到情况，就把这个issue重新打开。

玩不了一点，这回只有一组mod都不行。👀
![image](https://github.com/Trcmoe/LoadedModsExporter-Python/assets/145486869/03b71c1e-034f-464d-8cb7-251ae1aeeff6)
